version: '3'
services:
  app:
    build: .
    container_name: hapi
    ports:
     - 8082:8000
    links:
     - database
    env_file:
     - .env
    networks:
     - back
    volumes:
     - ./:/app
  database:
    image: mysql
    container_name: hapi_db
    networks:
     - back
    environment:
       MYSQL_ROOT_PASSWORD: 123
    ports: 
     - 33060:3306

networks:
  back:
    driver: bridge