version: '3'
services:
  app:
    build: .
    container_name: hapi
    ports:
     - 8000:8000
    env_file:
     - .env
    networks:
     - db-net
    volumes:
     - ./:/app
    depends_on: 
     - db

  db:
    build: ./src/db
    hostname: db
    container_name: hapi_db
    restart: always
    networks:
     - db-net
    ports: 
     - 33060:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    

networks:
  db-net: